default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test_guru_development

test:
  <<: *default
  database: test_guru_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
